version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: laminas_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: my_laminas
      MYSQL_USER: alexandr
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laminas_network

volumes:
  db_data:

networks:
  laminas_network:
    driver: bridge
