<h1>Users</h1>
<p>
    <a href="<?= $this->url('user', ['action' => 'add']) ?>">Add User</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user): ?>
        <tr>
            <td><?= $this->escapeHtml($user->name) ?></td>
            <td><?= $this->escapeHtml($user->email) ?></td>
            <td>
                <a href="<?= $this->url('user', ['action' => 'edit', 'id' => $user->id]) ?>">Edit</a>
            </td>
            <td>
                <a href="<?= $this->url('user', ['action' => 'delete', 'id' => $user->id]) ?>">Delete</a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
